name: drone-test
kind: pipeline
type: docker

steps:
- name: master-test
  image: alpine
  commands:
  - echo "Master was affected"
  when:
    branch: master
    event: push
- name: rel-tag
  image: alpine
  commands:
  - echo "A release* tag was pushed"
  when:
    event: tag
    tag: release*
- name: dev-test
  image: alpine
  commands:
  - echo "Dev was affected"
  when:
    branch: dev
    event: push
 