name: drone-test
kind: pipeline
type: docker

steps:
- name: master-test
  image: alpine
  commands:
  - echo "Master was affected"
  when:
    branch: master
    event: push
- name: master-tag
  image: alpine
  commands:
  - echo "Master was tagged and merged"
  when:
    branch: master
    event: push
    tag: release*
    
- name: dev-test
  image: alpine
  commands:
  - echo "Dev was affected"
  when:
    branch: dev
- name: tag-test
  image: alpine
  commands:
  - echo "A tag was published!"
  when:
    event: tag
 